Disease/help strings
duysqubix/scrolls pull request #53
Opened 2020-12-17 03:59 UTC by j3b4

Edited a copy of help_entries/races.py  to create help_entries/diseases.py.  Then I started adding the doc strings to the empty classes in world/diseases.py .  No idea what will go on behind the scene.

I'm using UESRPG text for the disease descriptions but have taken the liberty to make the mechanics more vague so as not to give players inaccurate or distracting information.  I could change this to just put in the numbers from the RPG verbatim ie.  -50 Magicka  ; and roll d100 after one week.   

Let me know what you think.

2020-12-17 04:16 UTC, duysqubix commented
I will check it out in the morning to see if it updates fine. From the looks of it, it should work as expected.

2020-12-17 04:22 UTC, duysqubix commented
Immediately what I can see though is that you will have to add a module level variable of 

```
ALL_DISEASES
```

That is a list of the class names. Such as 

```python
ALL_DISEASES = [Ataxia, Brainrot,...]

```

So that the wrapper can iterate through the static classes and access the \_\_doc\_\_ string

2020-12-17 04:24 UTC, duysqubix requested changes
Need to add an ALL_DISEASES list here.

2020-12-17 04:31 UTC, duysqubix requested changes

2020-12-17 04:31 UTC, duysqubix commented on resources/help_entries/diseases.py
> +for sign in ALL_DISEASES:
I think you meant to use disease instead of sign

2020-12-17 04:31 UTC, duysqubix commented on resources/help_entries/diseases.py
> +diseases = ", ".join([x.name.capitalize() for x in ALL_DISEASES])
In order to get the name of all diseases you need to have a way of actually getting it. 

For signs (which I see you copy/pasted from) the list of all signs is initialized which is why I you can access the property of `name` 

Diseases doesn't have that (not yet anyways) so you could access class name variable like `__name__` such as 

```python
diseases = [x.__name__ for x in ALL_DISEASES]
```

2020-12-17 13:01 UTC, j3b4 commented
Is something like this okay:   

`class BoneBreak(Disease):
    """
    """
    __obj_name__ = "bone break fever"
    pass`

_obj_name__ is what is used in world/races.py and world/birthsigns.py and in help_entries both races and birthsigns use  string = ", ".join([x.name.capitalize()

Just wondering if I should follow your example in the comment above or in your code.

2020-12-17 13:19 UTC, duysqubix commented
Oh yea if I do that then go for it. Help entries is one of the first things I did quite a while ago. Memory is a bit rusty.

2020-12-17 18:42 UTC, duysqubix commented
Finally at a computer @j3b4 
I see that I haven't even touched Diseases yet. You can continue using the same pattern like I do for Races and Conditions by using

`__obj_name__` if you plan on using the code of 

```python
diseases = [x.name.capitalize() for x in ALL_DISEASES]
```

Then you will need to have the following done for the parent class of Disease something like this:

```python

class Disease:
    __obj_name__ = ""
   
   @property
   def name(self):
      return self.__obj_name__

class BrainRot(Disease):
   __obj_name__ = "brain_rot" #try to refrain from using spaces, replace with _

class Fever(Disease):
   __obj_name__ = "fever"

ALL_DISEASES = [BrainRot(), Fever()]

```

2020-12-18 23:31 UTC, j3b4 commented
Okay this completes the docstrings for diseases. The main descriptions are verbatim (except for typos I noticed in the original) UESRPG 3e (version 3) but "symptoms" and "progression" have been edited to avoid describing mechanics that may or may not be reflected in the MUD code.

2020-12-19 02:10 UTC, duysqubix commented
Ha. The coronavirus was a nice touch.

2020-12-20 00:05 UTC, j3b4 commented
Added the name method to Disease() and replaced spaces with underscores in names.

2020-12-20 01:16 UTC, duysqubix commented
Very nice. I'll checkout latest to see if it successfully updates help entries on diseases.

2020-12-20 01:49 UTC, duysqubix commented on resources/help_entries/diseases.py
> +class RaceSignHelpEntry(HelpEntryWrapper):
Think you meant **DiseaseHelpEntry**

2020-12-20 01:49 UTC, duysqubix commented on world/diseases.py
> +
Missing a ending block comment here

"""

2020-12-20 01:49 UTC, duysqubix commented on world/diseases.py
> +    Cliff Racers
Ha. Cliff racers

2020-12-20 02:01 UTC, duysqubix commented
So I have made some minor changes to the PR to have it work properly.

I would recommend removing the sections in the `diseases` it messes up the formatting.

2020-12-22 02:20 UTC, duysqubix approved these changes

2020-12-22 07:44 UTC, merged